// Claude Skills Directory — full dataset.
// Sources: github.com/anthropics/skills, github.com/anthropics/claude-code,
// docs.claude.com, public community skill libraries, MCP plugin catalogs.
// Categories: official | builtin | community | mcp | experimental

window.SKILLS = [

  /* ============================================================
     OFFICIAL — Anthropic / claude.ai capability skills
     Source: github.com/anthropics/skills (document-skills, artifact-skills)
     ============================================================ */

  {
    slug: "pdf",
    name: "pdf",
    emoji: "📄",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "API", "Claude Code"],
    summary: "Read, fill, and create PDF documents — including forms, annotations, and merged outputs.",
    description: "Comprehensive PDF processing. Extract text and tables from existing PDFs, fill interactive form fields, merge or split documents, add annotations, and generate brand-new PDFs from markdown or HTML. Uses pypdf, pdfplumber, and reportlab under the hood.",
    triggers: ["pdf", "fill this form", "extract from PDF", "merge PDFs"],
    install: "Available by default on claude.ai. For Claude Code: `cp -r anthropics-skills/document-skills/pdf ~/.claude/skills/`. For API: add `\"pdf\"` to `container.skills`.",
    tools: ["Read", "Write", "Bash"],
    repo: "https://github.com/anthropics/skills/tree/main/document-skills/pdf"
  },
  {
    slug: "docx",
    name: "docx",
    emoji: "📝",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "API", "Claude Code"],
    summary: "Create and edit Microsoft Word documents with tracked-changes, styles, headers, and tables.",
    description: "Generates and modifies .docx files using python-docx. Supports tracked changes, custom styles, headers/footers, tables, images, and bookmarks. Ideal for reports, contracts, and any structured prose deliverable.",
    triggers: ["word document", "docx", "write a report", "tracked changes"],
    install: "On claude.ai: enabled by default. Claude Code: copy from `document-skills/docx`. API: include in `container.skills`.",
    tools: ["Read", "Write", "Bash"],
    repo: "https://github.com/anthropics/skills/tree/main/document-skills/docx"
  },
  {
    slug: "xlsx",
    name: "xlsx",
    emoji: "📊",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "API", "Claude Code"],
    summary: "Build and edit Excel spreadsheets with formulas, formatting, charts, and pivot tables.",
    description: "Uses openpyxl to generate .xlsx files with formulas, conditional formatting, charts, multiple sheets, named ranges, and pivot tables. Read existing workbooks, write data back, or generate financial models from scratch.",
    triggers: ["excel", "xlsx", "spreadsheet", "pivot table", "financial model"],
    install: "Same as other document skills — bundled on claude.ai, copy folder for Claude Code, list in `container.skills` for API.",
    tools: ["Read", "Write", "Bash"],
    repo: "https://github.com/anthropics/skills/tree/main/document-skills/xlsx"
  },
  {
    slug: "pptx",
    name: "pptx",
    emoji: "🎬",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "API", "Claude Code"],
    summary: "Generate PowerPoint decks with slides, layouts, charts, speaker notes, and images.",
    description: "Builds .pptx files via python-pptx. Supports master slides, custom layouts, embedded charts, images, speaker notes, and theme tokens. Pairs well with `web-design` for visually consistent decks.",
    triggers: ["powerpoint", "pptx", "slide deck", "presentation"],
    install: "Same as other document skills.",
    tools: ["Read", "Write", "Bash"],
    repo: "https://github.com/anthropics/skills/tree/main/document-skills/pptx"
  },
  {
    slug: "artifacts-builder",
    name: "artifacts-builder",
    emoji: "🎨",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "API"],
    summary: "Build sophisticated React + Tailwind artifacts inside Claude's artifact sandbox.",
    description: "Reference guide for the artifact runtime: available React libraries (recharts, lucide, framer-motion, shadcn), import patterns, sandbox constraints, and best practices for multi-file artifacts. Skill triggers when users ask for interactive UIs, dashboards, or visualisations.",
    triggers: ["build an artifact", "interactive component", "react app preview"],
    install: "Loaded automatically on claude.ai when artifacts are enabled.",
    tools: ["Read", "Write"],
    repo: "https://github.com/anthropics/skills/tree/main/artifacts-builder-skills/artifacts-builder"
  },
  {
    slug: "web-design",
    name: "web-design",
    emoji: "🌐",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Design tasteful, modern web pages with vetted color palettes, typography, and layouts.",
    description: "A taste primer: curated font pairings, color systems, spacing scales, and example layouts so Claude produces sites that don't look generic-AI. Use it whenever you generate landing pages, marketing sites, or dashboards.",
    triggers: ["landing page", "design a website", "marketing site"],
    install: "Copy `artifacts-builder-skills/webdesign` into `.claude/skills/`.",
    tools: ["Read", "Write"],
    repo: "https://github.com/anthropics/skills/tree/main/artifacts-builder-skills/webdesign"
  },
  {
    slug: "slack-gif-creator",
    name: "slack-gif-creator",
    emoji: "🎞️",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Compose looping Slack-sized GIFs from prompts or source media.",
    description: "Combines image generation + ffmpeg to produce optimised, sub-2MB GIFs sized for Slack/Discord reactions. Includes presets for common reaction types (party, shipping, ack).",
    triggers: ["make a gif", "reaction gif", "slack emoji"],
    install: "Clone from `anthropics/skills/artifacts-builder-skills/slack-gif-creator`.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/anthropics/skills/tree/main/artifacts-builder-skills/slack-gif-creator"
  },
  {
    slug: "mcp-builder",
    name: "mcp-builder",
    emoji: "🧰",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Scaffold a new MCP (Model Context Protocol) server in TypeScript or Python.",
    description: "Generates a complete MCP server with example tools, resource definitions, transport (stdio or HTTP), and a ready-to-publish package.json or pyproject.toml. Includes test harness and Claude Code install command.",
    triggers: ["build mcp server", "new mcp", "model context protocol"],
    install: "Drop into `~/.claude/skills/mcp-builder/`.",
    tools: ["Bash", "Write", "Edit"],
    repo: "https://github.com/anthropics/skills/tree/main/skill-creator-skills/mcp-builder"
  },
  {
    slug: "skill-creator",
    name: "skill-creator",
    emoji: "✨",
    category: "official",
    source: "anthropics/skills",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Bootstrap a new Claude skill — frontmatter, structure, scripts, and best-practice patterns.",
    description: "Walks you through naming, writing the description (so it triggers reliably), declaring allowed-tools, deciding what to inline vs. lazy-load, and packaging your skill folder. Includes templates for Python, Bash, and pure-markdown skills.",
    triggers: ["create a skill", "new skill", "skill scaffolding"],
    install: "Available via `npx claude-code skill new` or copy `skill-creator-skills/skill-creator` manually.",
    tools: ["Write", "Edit"],
    repo: "https://github.com/anthropics/skills/tree/main/skill-creator-skills/skill-creator"
  },

  /* ============================================================
     BUILT-IN — Skills bundled with Claude Code
     These ship inside the CLI and are advertised in the skills list.
     ============================================================ */

  {
    slug: "init",
    name: "init",
    emoji: "🚀",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Initialize a CLAUDE.md file documenting a codebase for future sessions.",
    description: "Run `/init` in a fresh repo to generate a CLAUDE.md: the architecture summary, key commands, conventions, and gotchas. Future sessions automatically load it on startup. Best first thing to run when onboarding Claude Code to a new project.",
    triggers: ["/init", "initialize claude.md", "onboard claude to repo"],
    install: "Bundled with Claude Code. Invoke with `/init`.",
    tools: ["Read", "Glob", "Grep", "Write"],
    repo: "https://docs.claude.com/en/docs/claude-code/memory"
  },
  {
    slug: "review",
    name: "review",
    emoji: "👀",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Run a structured pull request review on the current branch or a GitHub PR.",
    description: "Diffs against the base branch and produces a categorised review: bugs, style nits, security concerns, test gaps, design questions. Accepts a PR number to fetch via gh CLI.",
    triggers: ["/review", "review this PR", "review my branch"],
    install: "Built in. `/review` with no args reviews the local diff; `/review 123` pulls PR #123.",
    tools: ["Bash", "Read", "Grep"],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "security-review",
    name: "security-review",
    emoji: "🔒",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Sweep the diff for OWASP-style issues: injection, auth bypass, leaked secrets, unsafe deserialization.",
    description: "Runs through a security checklist tuned for code review: SQL/command injection vectors, missing authn/authz, secrets committed, unsafe parsers, SSRF, race conditions. Produces severity-ranked findings.",
    triggers: ["/security-review", "is this secure", "security audit branch"],
    install: "Bundled. Invoke with `/security-review`.",
    tools: ["Bash", "Read", "Grep"],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "verify",
    name: "verify",
    emoji: "✅",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Actually run the app and observe behaviour to confirm a change works — not just `npm test`.",
    description: "Starts the project's dev server or CLI, exercises the golden-path flow, and reports back. Useful for catching cases where unit tests pass but the feature is visibly broken.",
    triggers: ["/verify", "does this actually work", "test the change manually"],
    install: "Built in.",
    tools: ["Bash", "Read"],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "simplify",
    name: "simplify",
    emoji: "🧹",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Review changed code for duplication, dead code, and over-abstraction, then fix what's worth fixing.",
    description: "Looks at the diff with a 'less is more' lens: collapses near-duplicate functions, deletes unused imports, removes premature abstractions, and tightens names.",
    triggers: ["/simplify", "clean this up", "remove duplication"],
    install: "Built in.",
    tools: ["Read", "Edit", "Grep"],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "schedule",
    name: "schedule",
    emoji: "⏰",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Create, list, and manage scheduled (cron-style) remote Claude agents.",
    description: "Schedules recurring or one-off runs of a prompt or slash command — for example, 'check open PRs every morning at 9am' or 'remind me to roll the feature flag on March 1st'.",
    triggers: ["/schedule", "remind me", "run this daily"],
    install: "Built in. Backed by the Claude Routines feature.",
    tools: ["Bash"],
    repo: "https://docs.claude.com/en/docs/claude-code/routines"
  },
  {
    slug: "loop",
    name: "loop",
    emoji: "🔁",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Run a prompt or slash command on a recurring interval inside the current session.",
    description: "`/loop 5m /babysit-prs` keeps invoking the command every 5 minutes. Omit the interval to let Claude self-pace based on what it's waiting on.",
    triggers: ["/loop", "keep checking", "poll until done"],
    install: "Built in.",
    tools: [],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "claude-api",
    name: "claude-api",
    emoji: "🔌",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Build, debug, and tune apps that call the Anthropic SDK — caching, thinking, batch, tool use, files, citations.",
    description: "Triggers when you edit code that imports `anthropic` or `@anthropic-ai/sdk`. Adds prompt caching by default, knows current model IDs, and helps migrate between Claude versions.",
    triggers: ["anthropic sdk", "claude api", "prompt caching"],
    install: "Built in.",
    tools: ["Read", "Edit", "Bash"],
    repo: "https://docs.claude.com/en/api/getting-started"
  },
  {
    slug: "run",
    name: "run",
    emoji: "▶️",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Launch the project's app (CLI, server, TUI, Electron, browser) to verify a change end-to-end.",
    description: "Looks for an existing project skill that already knows how to run the app; otherwise falls back to per-project-type patterns. Use when 'tests pass' isn't proof enough.",
    triggers: ["/run", "start the app", "show me it working"],
    install: "Built in.",
    tools: ["Bash"],
    repo: "https://docs.claude.com/en/docs/claude-code/slash-commands"
  },
  {
    slug: "update-config",
    name: "update-config",
    emoji: "⚙️",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Edit ~/.claude/settings.json — permissions, env vars, hooks, model selection.",
    description: "Use whenever the user says 'allow X', 'whenever Y, do Z' (hooks), 'set env DEBUG=1', or wants to move a permission between user/project scope.",
    triggers: ["allow command", "add hook", "set env var"],
    install: "Built in.",
    tools: ["Read", "Edit"],
    repo: "https://docs.claude.com/en/docs/claude-code/settings"
  },
  {
    slug: "keybindings-help",
    name: "keybindings-help",
    emoji: "⌨️",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Customise ~/.claude/keybindings.json — rebind keys, add chord bindings, change the submit key.",
    description: "Walks you through the keybinding schema and writes the change. Handles chord bindings, mode-specific bindings, and conflict resolution.",
    triggers: ["rebind", "keyboard shortcut", "submit key"],
    install: "Built in.",
    tools: ["Read", "Edit"],
    repo: "https://docs.claude.com/en/docs/claude-code/settings"
  },
  {
    slug: "fewer-permission-prompts",
    name: "fewer-permission-prompts",
    emoji: "🛡️",
    category: "builtin",
    source: "claude-code",
    surfaces: ["Claude Code"],
    summary: "Scan transcripts for repetitive permission prompts and add a curated allowlist to .claude/settings.json.",
    description: "Looks at recent sessions, identifies safe read-only Bash + MCP calls you keep approving, and proposes a permissions block that eliminates the friction without granting writes.",
    triggers: ["stop asking permission", "permission noise", "allowlist"],
    install: "Built in.",
    tools: ["Read", "Edit"],
    repo: "https://docs.claude.com/en/docs/claude-code/permissions"
  },

  /* ============================================================
     OFFICIAL FIGMA — claude.ai Figma skills (paired with the MCP server)
     ============================================================ */

  {
    slug: "figma-use",
    name: "figma-use",
    emoji: "🎨",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "MANDATORY pre-flight skill before calling `use_figma`. Loads the right context to push designs into Figma.",
    description: "Sets up the calling pattern, design system selection, naming conventions, and frame structure expected by Figma before code-to-design generation. Skipping this skill yields broken Figma output.",
    triggers: ["use_figma", "push to figma", "make this a figma file"],
    install: "Activated automatically when the Figma MCP server is connected.",
    tools: ["mcp__claude_ai_Figma__*"],
    repo: "https://help.figma.com/hc/en-us/articles/32132100833559"
  },
  {
    slug: "figma-generate-design",
    name: "figma-generate-design",
    emoji: "🖼️",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Translate an app page or layout description into a structured Figma file.",
    description: "Best skill when going from a written spec, screenshot, or code page into a Figma file with proper frames, auto-layout, and components from a chosen library.",
    triggers: ["mock this up in figma", "design from spec", "figma from code"],
    install: "Auto via Figma MCP.",
    tools: ["mcp__claude_ai_Figma__*"],
    repo: "https://help.figma.com/hc/en-us/articles/32132100833559"
  },
  {
    slug: "figma-generate-library",
    name: "figma-generate-library",
    emoji: "📚",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Build a Figma design system / component library from existing codebase components.",
    description: "Reads your React/Vue component code, extracts the visual primitives, and produces a matching Figma library — buttons, inputs, cards, etc. — with variants and design tokens.",
    triggers: ["build design system in figma", "library from code"],
    install: "Auto via Figma MCP.",
    tools: ["mcp__claude_ai_Figma__*"],
    repo: "https://help.figma.com/hc/en-us/articles/32132100833559"
  },
  {
    slug: "figma-code-connect",
    name: "figma-code-connect",
    emoji: "🔗",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Map Figma components to codebase components so Dev Mode shows the right code.",
    description: "Walks through generating Code Connect mappings, validating them, and publishing them so designers and engineers see consistent component identity.",
    triggers: ["code connect", "map figma to code"],
    install: "Auto via Figma MCP.",
    tools: ["mcp__claude_ai_Figma__add_code_connect_map", "mcp__claude_ai_Figma__get_code_connect_map"],
    repo: "https://www.figma.com/code-connect-docs/"
  },
  {
    slug: "figma-use-figjam",
    name: "figma-use-figjam",
    emoji: "🧠",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "FigJam-specific generation: sticky notes, diagrams, brainstorms, retros.",
    description: "Knows the FigJam node types and layout conventions. Use it for free-form whiteboard content rather than design files.",
    triggers: ["figjam", "sticky notes", "retro board"],
    install: "Auto via Figma MCP.",
    tools: ["mcp__claude_ai_Figma__get_figjam", "mcp__claude_ai_Figma__use_figma"],
    repo: "https://help.figma.com/hc/en-us/articles/32132100833559"
  },
  {
    slug: "figma-generate-diagram",
    name: "figma-generate-diagram",
    emoji: "📐",
    category: "official",
    source: "claude.ai Figma MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "MANDATORY pre-flight before `generate_diagram`. Sets up structure for system, flow, or architecture diagrams.",
    description: "Loads diagram type templates (flow, sequence, ERD, architecture) and node-naming patterns so the resulting FigJam diagram is legible and editable.",
    triggers: ["draw a diagram", "system diagram", "architecture diagram"],
    install: "Auto via Figma MCP.",
    tools: ["mcp__claude_ai_Figma__generate_diagram"],
    repo: "https://help.figma.com/hc/en-us/articles/32132100833559"
  },

  /* ============================================================
     OFFICIAL — Anthropic Cookbook & blog-published skills
     ============================================================ */

  {
    slug: "data-analysis",
    name: "data-analysis",
    emoji: "📈",
    category: "official",
    source: "anthropic-cookbook",
    surfaces: ["claude.ai", "API"],
    summary: "Run pandas / NumPy analysis on uploaded CSVs and Parquet with sensible defaults.",
    description: "Loads with pandas already imported, sets sane display options, knows common cleaning patterns, and ships templates for common analyses: cohort retention, funnel, A/B test significance.",
    triggers: ["analyze this csv", "data analysis", "pandas"],
    install: "Anthropic Cookbook skill. Copy into `.claude/skills/` or list in API container.",
    tools: ["Bash", "Read", "Write"],
    repo: "https://github.com/anthropics/anthropic-cookbook"
  },
  {
    slug: "image-edit",
    name: "image-edit",
    emoji: "🖌️",
    category: "official",
    source: "anthropic-cookbook",
    surfaces: ["claude.ai"],
    summary: "Crop, resize, recolor, and composite images with PIL + ffmpeg defaults.",
    description: "Standard library of image operations: background removal via rembg, batch resize, watermark, format conversion, EXIF strip. Triggers on uploads ending in .png/.jpg/.webp.",
    triggers: ["crop image", "resize", "remove background"],
    install: "Cookbook skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/anthropics/anthropic-cookbook"
  },
  {
    slug: "video-edit",
    name: "video-edit",
    emoji: "🎥",
    category: "official",
    source: "anthropic-cookbook",
    surfaces: ["claude.ai"],
    summary: "Trim, concatenate, transcode, and add subtitles to video using ffmpeg.",
    description: "Wraps ffmpeg with helpers for common edits: silence removal, vertical-to-square reframe, subtitle burn-in, GIF export.",
    triggers: ["edit this video", "trim mp4", "burn subtitles"],
    install: "Cookbook skill.",
    tools: ["Bash"],
    repo: "https://github.com/anthropics/anthropic-cookbook"
  },
  {
    slug: "ocr",
    name: "ocr",
    emoji: "🔎",
    category: "official",
    source: "anthropic-cookbook",
    surfaces: ["claude.ai"],
    summary: "Extract text from scanned documents and images using Tesseract + layout heuristics.",
    description: "OCR with layout preservation. Outputs markdown with headings, lists, and tables inferred from spatial structure — not just a wall of text.",
    triggers: ["ocr", "scanned pdf", "extract text from image"],
    install: "Cookbook skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/anthropics/anthropic-cookbook"
  },

  /* ============================================================
     MCP — Skills that ship as part of plugin/MCP server bundles
     ============================================================ */

  {
    slug: "playwright-test",
    name: "playwright-test",
    emoji: "🎭",
    category: "mcp",
    source: "Playwright MCP",
    surfaces: ["Claude Code"],
    summary: "Drive a real browser via Playwright to verify UI changes, take screenshots, and run E2E flows.",
    description: "Pairs with the Playwright MCP server. Opens the dev server, navigates, clicks, asserts, and returns screenshots. Used by `/verify` for browser-based projects.",
    triggers: ["test in browser", "screenshot the page", "playwright"],
    install: "`claude mcp add playwright npx @playwright/mcp@latest` — skill auto-loads when the MCP is present.",
    tools: ["mcp__playwright__*"],
    repo: "https://github.com/microsoft/playwright-mcp"
  },
  {
    slug: "puppeteer-screenshot",
    name: "puppeteer-screenshot",
    emoji: "📸",
    category: "mcp",
    source: "Puppeteer MCP",
    surfaces: ["Claude Code"],
    summary: "Headless Chrome screenshots and DOM scraping via the Puppeteer MCP.",
    description: "Lighter-weight alternative to playwright-test when you only need a screenshot or to scrape a server-rendered page.",
    triggers: ["screenshot url", "scrape this page"],
    install: "Install the Puppeteer MCP server, then add the bundled skill.",
    tools: ["mcp__puppeteer__*"],
    repo: "https://github.com/modelcontextprotocol/servers"
  },
  {
    slug: "github-pr-ops",
    name: "github-pr-ops",
    emoji: "🐙",
    category: "mcp",
    source: "GitHub MCP",
    surfaces: ["Claude Code"],
    summary: "Open, comment on, merge, and review GitHub PRs without leaving the chat.",
    description: "Adds high-level PR workflows on top of the GitHub MCP: triage open PRs, request reviewers, summarise threads, merge with squash.",
    triggers: ["open pr", "merge pr", "list open prs"],
    install: "`claude mcp add github @modelcontextprotocol/server-github` — bring your own GITHUB_TOKEN.",
    tools: ["mcp__github__*"],
    repo: "https://github.com/github/github-mcp-server"
  },
  {
    slug: "linear-triage",
    name: "linear-triage",
    emoji: "📋",
    category: "mcp",
    source: "Linear MCP",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Pull a Linear ticket into context, draft a fix, and update status from chat.",
    description: "Reads ticket body + comments, finds the relevant code via codebase grep, opens a branch, and updates the ticket as work progresses.",
    triggers: ["linear ticket", "work on LIN-123"],
    install: "Install Linear MCP via Claude Desktop or Code, then enable the skill.",
    tools: ["mcp__linear__*"],
    repo: "https://linear.app/changelog/2024-11-06-mcp"
  },
  {
    slug: "notion-sync",
    name: "notion-sync",
    emoji: "🗒️",
    category: "mcp",
    source: "Notion MCP",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Read and write Notion pages, databases, and properties from a chat session.",
    description: "Great for keeping spec docs, retrospectives, and OKRs in sync with what's actually shipping. Includes patterns for database row creation and property updates.",
    triggers: ["update notion", "create notion page"],
    install: "Notion MCP server + OAuth.",
    tools: ["mcp__notion__*"],
    repo: "https://developers.notion.com/"
  },
  {
    slug: "slack-ops",
    name: "slack-ops",
    emoji: "💬",
    category: "mcp",
    source: "Slack MCP",
    surfaces: ["Claude Code"],
    summary: "Search Slack history, post messages, react, and start threads from Claude.",
    description: "Adds opinionated patterns on top of the raw Slack MCP — composing summary threads, posting deploy notifications, and surfacing relevant past discussions.",
    triggers: ["post to slack", "find slack thread"],
    install: "Install Slack MCP, scope a bot token, enable the skill.",
    tools: ["mcp__slack__*"],
    repo: "https://github.com/modelcontextprotocol/servers"
  },
  {
    slug: "gdrive-search",
    name: "gdrive-search",
    emoji: "📁",
    category: "mcp",
    source: "Google Drive MCP",
    surfaces: ["claude.ai"],
    summary: "Search across Google Drive and load relevant docs into context.",
    description: "Best for finding 'that one doc' in a sea of meeting notes. Uses semantic search if available, falls back to title + body keyword.",
    triggers: ["find in drive", "search google docs"],
    install: "Authenticate via `mcp__claude_ai_Google_Drive__authenticate`.",
    tools: ["mcp__claude_ai_Google_Drive__*"],
    repo: "https://github.com/modelcontextprotocol/servers"
  },
  {
    slug: "gcal-schedule",
    name: "gcal-schedule",
    emoji: "📅",
    category: "mcp",
    source: "Google Calendar MCP",
    surfaces: ["claude.ai"],
    summary: "Check availability, schedule meetings, and pull upcoming events from Google Calendar.",
    description: "Knows free/busy queries, recurring event patterns, and how to propose times across attendees.",
    triggers: ["schedule a meeting", "find a time"],
    install: "Authenticate via `mcp__claude_ai_Google_Calendar__authenticate`.",
    tools: ["mcp__claude_ai_Google_Calendar__*"],
    repo: "https://github.com/modelcontextprotocol/servers"
  },
  {
    slug: "postgres-query",
    name: "postgres-query",
    emoji: "🐘",
    category: "mcp",
    source: "Postgres MCP",
    surfaces: ["Claude Code"],
    summary: "Run read-only SQL against a Postgres database via the official Postgres MCP.",
    description: "Safe analytical queries — schema introspection, EXPLAIN ANALYZE, sampled SELECTs. Server defaults to read-only; writes require explicit configuration.",
    triggers: ["query postgres", "show me the table"],
    install: "`claude mcp add postgres @modelcontextprotocol/server-postgres` and pass a connection string.",
    tools: ["mcp__postgres__*"],
    repo: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres"
  },
  {
    slug: "sqlite-explorer",
    name: "sqlite-explorer",
    emoji: "🗃️",
    category: "mcp",
    source: "SQLite MCP",
    surfaces: ["Claude Code"],
    summary: "Open and query SQLite files — useful for analysing app local DBs and Chrome history.",
    description: "Read-only by default. Lists tables, sampling rows, and running ad-hoc analytical queries on .sqlite/.db files.",
    triggers: ["sqlite", "open .db file"],
    install: "Install the SQLite MCP server.",
    tools: ["mcp__sqlite__*"],
    repo: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite"
  },
  {
    slug: "stripe-ops",
    name: "stripe-ops",
    emoji: "💳",
    category: "mcp",
    source: "Stripe MCP",
    surfaces: ["Claude Code"],
    summary: "Issue refunds, look up customers, inspect subscriptions through the Stripe MCP.",
    description: "Helps customer-support and ops workflows. Read-by-default, with explicit confirmation for any write (refund, cancel).",
    triggers: ["stripe refund", "find stripe customer"],
    install: "Install Stripe MCP, supply restricted API key with a careful scope.",
    tools: ["mcp__stripe__*"],
    repo: "https://docs.stripe.com/building-with-llms"
  },
  {
    slug: "sentry-debug",
    name: "sentry-debug",
    emoji: "🐞",
    category: "mcp",
    source: "Sentry MCP",
    surfaces: ["Claude Code"],
    summary: "Pull Sentry issues, view stack traces, group similar errors, and link back to code.",
    description: "Best paired with the GitHub MCP — once you find the root frame, jump to the line in your repo and propose a fix.",
    triggers: ["sentry issue", "fix this error"],
    install: "Sentry MCP server, scope to project read.",
    tools: ["mcp__sentry__*"],
    repo: "https://docs.sentry.io/product/integrations/llms/mcp/"
  },

  /* ============================================================
     COMMUNITY — Popular open-source skill repositories
     ============================================================ */

  {
    slug: "commit-message-writer",
    name: "commit-message-writer",
    emoji: "✍️",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Produce conventional-commit messages from a staged diff.",
    description: "Reads `git diff --cached`, classifies the change (feat, fix, refactor, docs, chore), and writes a tight, project-style commit message. Optional scope inference from changed paths.",
    triggers: ["write commit message", "/commit"],
    install: "Copy from any of several community repos into `~/.claude/skills/commit-message-writer/`.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "test-writer-jest",
    name: "test-writer-jest",
    emoji: "🧪",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Generate Jest tests for changed JS/TS files with mocks scaffolded.",
    description: "Picks reasonable describe/it structure based on existing tests, mocks fetch/timers correctly, and prefers behavioural assertions over implementation snooping.",
    triggers: ["write jest tests", "test this file"],
    install: "Community skill — drop into `.claude/skills/test-writer-jest/`.",
    tools: ["Read", "Write", "Edit", "Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "test-writer-pytest",
    name: "test-writer-pytest",
    emoji: "🧪",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Generate pytest tests with fixtures and parametrize for changed Python files.",
    description: "Knows pytest conventions: fixtures over setUp, parametrize over loops, monkeypatch over manual patching. Prefers integration tests when DB or HTTP is involved.",
    triggers: ["write pytest", "test this python module"],
    install: "Community skill.",
    tools: ["Read", "Write", "Edit", "Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "changelog",
    name: "changelog",
    emoji: "📜",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Maintain a Keep-a-Changelog style CHANGELOG.md from recent commits.",
    description: "Reads `git log` since the last tag, groups commits into Added / Changed / Fixed / Removed, drafts the next version's entry. Optional semver suggestion.",
    triggers: ["update changelog", "release notes"],
    install: "Community skill.",
    tools: ["Bash", "Read", "Edit"],
    repo: "https://keepachangelog.com/"
  },
  {
    slug: "dependency-audit",
    name: "dependency-audit",
    emoji: "📦",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Audit package.json / pyproject.toml for outdated, vulnerable, or duplicate dependencies.",
    description: "Wraps `npm audit`, `pip-audit`, and `osv-scanner`. Groups results by severity and proposes upgrade paths, flagging breaking-change risk.",
    triggers: ["audit deps", "outdated packages"],
    install: "Community skill.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "i18n-extractor",
    name: "i18n-extractor",
    emoji: "🌍",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Find hardcoded UI strings and replace them with t() calls + locale JSON entries.",
    description: "Detects user-facing strings in JSX/Vue templates, suggests stable keys, updates the default locale file, and rewrites the source with `t('...')`. Works with react-i18next, vue-i18n, next-intl.",
    triggers: ["i18n", "extract strings", "translate ui"],
    install: "Community skill.",
    tools: ["Read", "Edit", "Grep"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "accessibility-review",
    name: "accessibility-review",
    emoji: "♿",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Audit React / HTML for WCAG issues — alt text, color contrast, focus traps, ARIA misuse.",
    description: "Runs axe-core via Playwright when possible, otherwise static checks. Reports findings with severity and a one-line fix suggestion.",
    triggers: ["a11y", "accessibility check"],
    install: "Community skill.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/dequelabs/axe-core"
  },
  {
    slug: "seo-audit",
    name: "seo-audit",
    emoji: "🔍",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Audit pages for SEO: titles, meta descriptions, OG tags, canonical, heading structure.",
    description: "Crawls a deployed URL or local dev server, scoring each page on a curated SEO checklist, with actionable fixes.",
    triggers: ["seo audit", "meta tags"],
    install: "Community skill.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "lighthouse-perf",
    name: "lighthouse-perf",
    emoji: "🚦",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Run Lighthouse on a URL and produce a prioritised perf-optimisation plan.",
    description: "Filters Lighthouse output to the highest-impact opportunities, links to the code that's likely the cause, and proposes concrete diffs.",
    triggers: ["lighthouse", "perf audit"],
    install: "Community skill. Requires Node + Lighthouse CLI installed.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/GoogleChrome/lighthouse"
  },
  {
    slug: "regex-explainer",
    name: "regex-explainer",
    emoji: "🧬",
    category: "community",
    source: "community",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Explain a regex token by token and list edge cases it does / doesn't match.",
    description: "Decomposes the regex into a railroad-diagram-style breakdown, then runs it against a generated test corpus to show concrete matches.",
    triggers: ["explain regex"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "sql-explainer",
    name: "sql-explainer",
    emoji: "🧮",
    category: "community",
    source: "community",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Explain a SQL query in plain English, then suggest indexes from the access pattern.",
    description: "Parses the query, walks through the logical execution, and proposes index changes that would make it cheaper. Works without a live database connection.",
    triggers: ["explain this query", "optimize sql"],
    install: "Community skill.",
    tools: [],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "k8s-debug",
    name: "k8s-debug",
    emoji: "☸️",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Triage a misbehaving Kubernetes workload — pods, events, logs, recent changes.",
    description: "Runs the standard diagnostic sweep: `kubectl get pods`, `describe`, `events`, `logs`, and `rollout history`. Surfaces the most likely cause and the next command to run.",
    triggers: ["pod crashing", "k8s issue"],
    install: "Community skill. Requires kubectl in PATH.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "docker-tune",
    name: "docker-tune",
    emoji: "🐳",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Review Dockerfiles for size, caching, security, and reproducibility issues.",
    description: "Hadolint-style checks plus opinionated patterns: multi-stage builds, pinned base images, non-root user, .dockerignore.",
    triggers: ["review dockerfile", "shrink image"],
    install: "Community skill.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/hadolint/hadolint"
  },
  {
    slug: "terraform-plan-review",
    name: "terraform-plan-review",
    emoji: "🏗️",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Review a `terraform plan` for destructive changes, drift, and policy violations.",
    description: "Parses the JSON plan, classifies each resource action (create/update/destroy/replace), and warns on production-sensitive resources before apply.",
    triggers: ["review terraform plan"],
    install: "Community skill.",
    tools: ["Bash", "Read"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "git-bisect",
    name: "git-bisect",
    emoji: "🪓",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Run git bisect with an automated test command to find the offending commit.",
    description: "Sets up `git bisect start`, drives the loop with a user-provided test command, and reports the first-bad commit with the diff highlighted.",
    triggers: ["bisect", "find regression"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://git-scm.com/docs/git-bisect"
  },
  {
    slug: "log-grok",
    name: "log-grok",
    emoji: "📑",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Parse a giant log file, cluster errors, and surface the top failure modes.",
    description: "Streams the log without loading it all into context, hashes lines into clusters, and reports the top N error signatures with sample lines and counts.",
    triggers: ["parse log", "what's failing"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "api-spec-from-code",
    name: "api-spec-from-code",
    emoji: "📡",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Generate an OpenAPI 3 spec from existing Express / FastAPI / Rails routes.",
    description: "Walks the router definitions, infers request/response shapes from validators and serializers, and writes a passing OpenAPI YAML.",
    triggers: ["generate openapi", "api spec"],
    install: "Community skill.",
    tools: ["Read", "Write", "Grep"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "graphql-explorer",
    name: "graphql-explorer",
    emoji: "🌐",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Introspect a GraphQL endpoint, run sample queries, and scaffold fragments.",
    description: "Hits the schema introspection endpoint, builds a queryable mental model, and helps write queries for the common entities.",
    triggers: ["graphql", "explore schema"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "readme-generator",
    name: "readme-generator",
    emoji: "📘",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Generate a high-quality README from the codebase: install, usage, examples, contributing.",
    description: "Detects the project type (Node, Python, Rust, Go, multi-language), pulls install commands from package metadata, and drafts a README with sections that match what the project actually does.",
    triggers: ["generate readme"],
    install: "Community skill.",
    tools: ["Read", "Write", "Glob"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "license-helper",
    name: "license-helper",
    emoji: "⚖️",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Recommend a license, generate the LICENSE file, and add SPDX headers to source.",
    description: "Asks about commercial use, copyleft preference, patent grant. Picks among MIT / Apache-2.0 / GPL / BSL and writes the canonical text.",
    triggers: ["add license", "which license"],
    install: "Community skill.",
    tools: ["Write", "Edit"],
    repo: "https://choosealicense.com/"
  },
  {
    slug: "story-board",
    name: "story-board",
    emoji: "🎬",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Generate a storyboard (panels + captions + prompts) for a short video or animation.",
    description: "Useful for explainers, product walkthroughs, and short marketing reels. Outputs a printable PDF storyboard plus per-panel image-generation prompts.",
    triggers: ["storyboard"],
    install: "Community skill.",
    tools: ["Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "uml-diagram",
    name: "uml-diagram",
    emoji: "📊",
    category: "community",
    source: "community",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Generate PlantUML / Mermaid diagrams from a code module or natural-language spec.",
    description: "Renders sequence, class, ER, state, and deployment diagrams. Outputs Mermaid for inline rendering and PlantUML for higher-fidelity exports.",
    triggers: ["draw uml", "mermaid diagram"],
    install: "Community skill.",
    tools: ["Write"],
    repo: "https://mermaid.js.org/"
  },
  {
    slug: "csv-cleaner",
    name: "csv-cleaner",
    emoji: "🧽",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Clean messy CSVs: dedupe, normalize columns, fix dates, infer types, report quality.",
    description: "Pandas-backed cleaning recipe. Outputs the cleaned file plus a quality report (nulls, duplicates, type mismatches).",
    triggers: ["clean csv", "messy data"],
    install: "Community skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "translate",
    name: "translate",
    emoji: "🌎",
    category: "community",
    source: "community",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Translate documents preserving formatting, code blocks, links, and front-matter.",
    description: "Best for technical docs, README files, and marketing copy. Preserves markdown structure, leaves code untranslated, and produces parallel files.",
    triggers: ["translate this", "to spanish"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "voice-transcribe",
    name: "voice-transcribe",
    emoji: "🎙️",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Transcribe audio uploads via Whisper, then produce a structured summary + action items.",
    description: "Local Whisper for the transcription, Claude for cleaning up disfluencies and pulling out action items, decisions, and open questions.",
    triggers: ["transcribe meeting"],
    install: "Community skill. Requires whisper.cpp or openai-whisper.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/openai/whisper"
  },
  {
    slug: "resume-tailor",
    name: "resume-tailor",
    emoji: "📃",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Tailor a base resume to a job description while keeping every claim truthful.",
    description: "Pulls keywords from the JD, reorders bullets, tightens phrasing, and outputs the result as DOCX or PDF. Refuses to invent experience.",
    triggers: ["tailor resume", "cover letter"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "invoice-builder",
    name: "invoice-builder",
    emoji: "🧾",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Generate a styled PDF invoice from line items, with auto-calculated tax and totals.",
    description: "Customisable templates, multi-currency support, optional QR for payment links. Outputs PDF + CSV for accounting import.",
    triggers: ["create invoice"],
    install: "Community skill.",
    tools: ["Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "calendar-ics",
    name: "calendar-ics",
    emoji: "🗓️",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Produce .ics calendar files from natural-language events or a list.",
    description: "Handles timezones, recurrence rules (RRULE), reminders, and attendees. Outputs a standards-compliant ICS that drops into Google / Apple Calendar.",
    triggers: ["create calendar event", ".ics"],
    install: "Community skill.",
    tools: ["Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "qr-batch",
    name: "qr-batch",
    emoji: "🔳",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Generate a sheet of QR codes from a CSV of URLs, with labels and a print layout.",
    description: "Useful for event check-ins, asset tagging, and physical-to-digital handoffs. Outputs a print-ready PDF and individual PNGs.",
    triggers: ["bulk qr", "qr sheet"],
    install: "Community skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "epub-export",
    name: "epub-export",
    emoji: "📚",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Bundle a folder of markdown into a styled EPUB with cover, TOC, and metadata.",
    description: "Uses pandoc + epubcheck. Supports custom CSS, embedded images, and chapter ordering by file name.",
    triggers: ["make epub"],
    install: "Community skill. Requires pandoc.",
    tools: ["Bash"],
    repo: "https://pandoc.org/"
  },
  {
    slug: "markdown-tidy",
    name: "markdown-tidy",
    emoji: "🧼",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Fix markdown: consistent headings, table alignment, link checking, dead-image cleanup.",
    description: "Runs markdownlint with sensible rules, fixes auto-fixable issues, and reports the rest. Optional link checker for HTTP 404s and broken anchors.",
    triggers: ["lint markdown"],
    install: "Community skill.",
    tools: ["Bash", "Edit"],
    repo: "https://github.com/DavidAnson/markdownlint"
  },
  {
    slug: "math-tutor",
    name: "math-tutor",
    emoji: "🧮",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Walk through math problems step-by-step using SymPy for symbolic verification.",
    description: "Doesn't just spit out answers — explains each step, validates with SymPy, and warns when a step changes the solution set.",
    triggers: ["solve this", "show me the math"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "chess-coach",
    name: "chess-coach",
    emoji: "♟️",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Analyse a PGN game with Stockfish, annotate blunders, and suggest study lines.",
    description: "Hosts a local Stockfish binary, evaluates each move, and produces a coach-style annotation track.",
    triggers: ["analyse my game", "pgn"],
    install: "Community skill. Requires stockfish binary in PATH.",
    tools: ["Bash"],
    repo: "https://stockfishchess.org/"
  },
  {
    slug: "deck-from-doc",
    name: "deck-from-doc",
    emoji: "📽️",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Convert a written doc into a presentation deck (pairs with `pptx` and `web-design`).",
    description: "Picks slide breaks, generates titles, drafts speaker notes, and applies a tasteful theme.",
    triggers: ["doc to slides"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "data-viz",
    name: "data-viz",
    emoji: "📉",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Produce publication-quality charts from CSVs with sensible chart-type selection.",
    description: "Picks the right chart for the data (avoid pies, prefer ordered bars, use small multiples), and outputs PNG + SVG with annotations.",
    triggers: ["chart this", "make a graph"],
    install: "Community skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "research-summary",
    name: "research-summary",
    emoji: "🔬",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Read a research paper PDF and produce a structured summary: claim, method, evidence, limits.",
    description: "Pulls figures and tables, summarises each section, and flags claims that aren't fully supported by the evidence shown.",
    triggers: ["summarise paper", "arxiv"],
    install: "Community skill — pairs with `pdf`.",
    tools: ["Read"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "spec-to-pr",
    name: "spec-to-pr",
    emoji: "📑",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Turn a written feature spec into a branch, scaffolded files, tests, and a draft PR.",
    description: "Reads the spec, plans the change, creates a branch, scaffolds the implementation, writes tests, and opens a draft PR with the spec referenced in the body.",
    triggers: ["spec to pr", "implement spec"],
    install: "Community skill.",
    tools: ["Bash", "Read", "Write", "Edit"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "incident-report",
    name: "incident-report",
    emoji: "🚨",
    category: "community",
    source: "community",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Draft a blameless post-incident report from timeline notes, logs, and chat history.",
    description: "Templates: summary, impact, timeline, contributing factors, what-went-well, action items. Encourages systemic thinking over individual blame.",
    triggers: ["postmortem", "incident report"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "okr-tracker",
    name: "okr-tracker",
    emoji: "🎯",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Maintain quarterly OKRs in a structured doc, with weekly check-in templates.",
    description: "Helps phrase objectives that are inspirational, key results that are measurable, and weekly notes that drive accountability without micromanagement.",
    triggers: ["okrs", "track goals"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "user-interview-synth",
    name: "user-interview-synth",
    emoji: "🗣️",
    category: "community",
    source: "community",
    surfaces: ["claude.ai"],
    summary: "Synthesise themes across user-interview transcripts using affinity-style clustering.",
    description: "Reads each transcript, extracts atomic insights, then clusters them into themes with evidence quotes attached.",
    triggers: ["user research", "interview synthesis"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "prompt-eval",
    name: "prompt-eval",
    emoji: "🧪",
    category: "community",
    source: "community",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Run a prompt over a labelled dataset and compute pass-rate + error breakdown.",
    description: "Pairs with `claude-api`. Loads a CSV of inputs and expected outputs, calls the model, and reports a confusion-matrix-style breakdown.",
    triggers: ["eval prompt", "prompt benchmark"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/anthropics/anthropic-cookbook"
  },
  {
    slug: "embeddings-search",
    name: "embeddings-search",
    emoji: "🧠",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Build a quick semantic search index over a folder of docs using Voyage / OpenAI embeddings.",
    description: "Chunks docs, embeds, stores in a local vector store (chroma or sqlite-vec), and answers queries with citations.",
    triggers: ["semantic search", "rag over docs"],
    install: "Community skill.",
    tools: ["Bash", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "ascii-art",
    name: "ascii-art",
    emoji: "🎨",
    category: "community",
    source: "community",
    surfaces: ["claude.ai", "Claude Code"],
    summary: "Generate ASCII art banners, box drawings, and small illustrations.",
    description: "Useful for CLI splash screens, README headers, and email signatures. Knows figlet fonts and box-drawing tricks.",
    triggers: ["ascii banner"],
    install: "Community skill.",
    tools: ["Bash"],
    repo: "https://github.com/topics/claude-skills"
  },

  /* ============================================================
     EXPERIMENTAL — Skills in active development or limited release
     ============================================================ */

  {
    slug: "voice-clone-narration",
    name: "voice-clone-narration",
    emoji: "🎤",
    category: "experimental",
    source: "experimental",
    surfaces: ["claude.ai"],
    summary: "Narrate a doc using a consented voice clone via an external TTS provider.",
    description: "Strictly gated: requires recorded consent from the voice owner. Outputs an MP3 with sentence-level timestamps for sync.",
    triggers: ["narrate this"],
    install: "Experimental — manual install only. Requires an ElevenLabs / equivalent API key.",
    tools: ["Bash"],
    repo: ""
  },
  {
    slug: "video-narration",
    name: "video-narration",
    emoji: "🎬",
    category: "experimental",
    source: "experimental",
    surfaces: ["claude.ai"],
    summary: "Generate a short product-walkthrough video from screenshots + a written script.",
    description: "Combines image-gen, TTS, and ffmpeg to produce a sub-60-second walkthrough. Best for landing-page hero videos.",
    triggers: ["product video"],
    install: "Experimental. Pairs with `video-edit` and `voice-clone-narration`.",
    tools: ["Bash"],
    repo: ""
  },
  {
    slug: "3d-cad-helper",
    name: "3d-cad-helper",
    emoji: "🧊",
    category: "experimental",
    source: "experimental",
    surfaces: ["Claude Code"],
    summary: "Generate OpenSCAD or CadQuery files for 3D-printable parts from a written spec.",
    description: "Useful for parametric brackets, enclosures, and replacement parts. Validates with a render before exporting STL.",
    triggers: ["openscad", "3d print"],
    install: "Experimental. Requires OpenSCAD or CadQuery installed locally.",
    tools: ["Bash", "Write"],
    repo: "https://openscad.org/"
  },
  {
    slug: "music-gen-helper",
    name: "music-gen-helper",
    emoji: "🎵",
    category: "experimental",
    source: "experimental",
    surfaces: ["claude.ai"],
    summary: "Compose short MIDI sketches with chord progressions and basic arrangement.",
    description: "Outputs a MIDI file plus a rendered MP3 preview. Style presets: lo-fi, ambient, cinematic, pop. Not a replacement for a producer.",
    triggers: ["compose music", "midi"],
    install: "Experimental.",
    tools: ["Bash"],
    repo: ""
  },
  {
    slug: "game-design-doc",
    name: "game-design-doc",
    emoji: "🎮",
    category: "experimental",
    source: "experimental",
    surfaces: ["claude.ai"],
    summary: "Draft a game design document (GDD) from a one-line pitch.",
    description: "Walks through: pillars, core loop, MDA, art direction, monetization, scope. Outputs a structured DOCX.",
    triggers: ["game design doc"],
    install: "Experimental.",
    tools: ["Write"],
    repo: ""
  },

  /* ============================================================
     COMMUNITY DESIGN / DEV — Pro-grade third-party skills
     ============================================================ */

  {
    slug: "ui-ux-pro-max",
    name: "ui-ux-pro-max",
    emoji: "🎨",
    category: "community",
    source: "uipro-cli (npm)",
    surfaces: ["Claude Code", "Cursor", "Windsurf", "Copilot"],
    summary: "Comprehensive UI/UX design intelligence — 67 styles, 96 palettes, 57 font pairings, 99 UX rules, 25 chart types across 13 tech stacks.",
    description: "Searchable design system database with priority-based recommendations. Covers accessibility (WCAG 4.5:1, focus, ARIA), touch targets, performance (image optimization, reduced-motion), layout (z-index scale, responsive), typography pairings, color palettes by industry, landing page structures, chart selection, and stack-specific best practices for React, Next.js, Vue, Svelte, SwiftUI, React Native, Flutter, Tailwind, and shadcn/ui. Includes a Python CLI (search.py) that queries CSV data for tailored recommendations.",
    triggers: ["design a", "build a landing page", "ui/ux review", "color palette", "design system", "make it look professional"],
    install: "Run `npm install -g uipro-cli` then `uipro init -a claude`. Drops a folder into `.claude/skills/ui-ux-pro-max/` with SKILL.md, scripts, and 11 CSV data files.",
    tools: ["Bash", "Read", "Write"],
    repo: "https://www.npmjs.com/package/uipro-cli"
  },
  {
    slug: "context7",
    name: "context7",
    emoji: "📚",
    category: "mcp",
    source: "Context7 MCP",
    surfaces: ["Claude Code", "claude.ai", "Cursor"],
    summary: "Live, up-to-date documentation for any library — fetched on demand inside the conversation.",
    description: "MCP server that pulls fresh docs for thousands of libraries (React, Tailwind, Stripe, AWS SDKs, etc.). Stops Claude from hallucinating APIs based on stale training data. Especially useful for fast-moving libraries.",
    triggers: ["context7", "use the docs for", "how do I use X library", "library reference"],
    install: "`claude mcp add context7 npx -y @upstash/context7-mcp` or via the Cursor/Claude Desktop MCP config.",
    tools: ["mcp__context7__*"],
    repo: "https://context7.com"
  },
  {
    slug: "deepwiki",
    name: "deepwiki",
    emoji: "🧭",
    category: "mcp",
    source: "DeepWiki MCP",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Ask questions of any public GitHub repo — DeepWiki indexes the codebase and serves AI-friendly answers.",
    description: "Connects Claude to deepwiki.com's indexed repos. Useful for understanding unfamiliar open-source projects without cloning them. Returns answers with file/line citations.",
    triggers: ["deepwiki", "explain this repo", "how does X library implement Y"],
    install: "`claude mcp add deepwiki npx -y @deepwiki/mcp` (or via the official MCP listing).",
    tools: ["mcp__deepwiki__*"],
    repo: "https://deepwiki.com"
  },
  {
    slug: "shadcn-ui",
    name: "shadcn-ui",
    emoji: "🧩",
    category: "mcp",
    source: "shadcn/ui MCP",
    surfaces: ["Claude Code", "claude.ai"],
    summary: "Browse, search, and scaffold shadcn/ui components straight into your project.",
    description: "MCP server that exposes the shadcn/ui component catalog: search by name or function, view source, and install with the right CLI command. Officially integrated into the Claude.ai Figma MCP for code-design parity.",
    triggers: ["shadcn", "add a shadcn component", "data table component"],
    install: "`claude mcp add shadcn npx -y @jpisnice/shadcn-ui-mcp-server` (or via plugin marketplace).",
    tools: ["mcp__shadcn__*"],
    repo: "https://ui.shadcn.com/docs/mcp"
  },
  {
    slug: "magic-mcp",
    name: "magic-mcp",
    emoji: "✨",
    category: "mcp",
    source: "21st.dev Magic",
    surfaces: ["Claude Code", "Cursor"],
    summary: "Generate polished React/Tailwind components from a description — 21st.dev's AI component library, accessible via MCP.",
    description: "Turns prompts like 'a pricing page with toggle and three tiers' into clean, accessible React + Tailwind components. Pulls from 21st.dev's curated library.",
    triggers: ["magic component", "generate a", "21st.dev component"],
    install: "`claude mcp add magic npx -y @21st-dev/magic-mcp` and supply a 21st.dev API key.",
    tools: ["mcp__magic__*"],
    repo: "https://21st.dev"
  },
  {
    slug: "claude-code-templates",
    name: "claude-code-templates",
    emoji: "📦",
    category: "community",
    source: "claude-code-templates (npm)",
    surfaces: ["Claude Code"],
    summary: "One-command installer for curated agents, commands, hooks, and skills — by language and framework.",
    description: "CLI that installs ready-made Claude Code configurations: language-specific subagents (rust-pro, python-pro, ts-pro), slash commands, hooks, and skill bundles. Useful for onboarding a project to Claude in minutes.",
    triggers: ["claude-code-templates", "install claude templates", "set up a Claude config"],
    install: "`npx claude-code-templates@latest` then pick from the menu, or `npx claude-code-templates@latest --skill <name>` for a specific one.",
    tools: ["Bash"],
    repo: "https://github.com/davila7/claude-code-templates"
  },
  {
    slug: "superdesign",
    name: "superdesign",
    emoji: "🖌️",
    category: "community",
    source: "community",
    surfaces: ["Claude Code", "Cursor"],
    summary: "AI design partner skill — generates mockups, iterates layouts, exports to Figma or code.",
    description: "Community design-focused skill. Pairs with `web-design` and `figma-use` for end-to-end flows from spec to Figma to code. Often bundled in design-focused plugins.",
    triggers: ["superdesign", "design a screen for", "iterate on this layout"],
    install: "Drop the skill folder into `~/.claude/skills/superdesign/` (clone from the GitHub source) — see the SuperDesign README.",
    tools: ["Read", "Write"],
    repo: "https://github.com/superdesign-ai/superdesign"
  },
  {
    slug: "cursor-rules-import",
    name: "cursor-rules-import",
    emoji: "📥",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Convert Cursor's `.cursorrules` and `.cursor/rules/` files into a Claude skill or CLAUDE.md.",
    description: "Useful when switching from Cursor to Claude Code, or maintaining both. Reads existing Cursor rule files and produces a structured CLAUDE.md or a per-feature skill folder.",
    triggers: ["import cursor rules", "port cursor config to claude"],
    install: "Community skill. Clone into `~/.claude/skills/cursor-rules-import/`.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-skills"
  },
  {
    slug: "claude-flow",
    name: "claude-flow",
    emoji: "🌊",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Multi-agent orchestration patterns — spawn subagents, route work, merge results.",
    description: "Skill that teaches Claude how to break large tasks into coordinated subagent runs. Pairs with the built-in subagent system. Includes templates for planner/executor/critic patterns.",
    triggers: ["multi-agent", "delegate this to subagents", "orchestrate"],
    install: "Community skill.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-code"
  },
  {
    slug: "agent-os",
    name: "agent-os",
    emoji: "🧠",
    category: "community",
    source: "community",
    surfaces: ["Claude Code"],
    summary: "Standards layer for product/spec/decision docs — gives Claude a consistent shape to plan in.",
    description: "Adds opinionated templates for product specs, design docs, ADRs, and post-mortems. Claude reads from a `.agent-os/` folder when planning, keeping output consistent across teammates.",
    triggers: ["agent-os", "write a spec", "ADR for this decision"],
    install: "Community skill. See the Agent OS repo for the bootstrap script.",
    tools: ["Read", "Write"],
    repo: "https://github.com/topics/claude-code"
  }
];

// Highlighted on the home page (first 6 cards).
window.FEATURED_SLUGS = [
  "ui-ux-pro-max", "context7", "shadcn-ui", "pdf", "skill-creator", "security-review"
];
